# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWP-UserAgent-iTMS_Client
version:      0.04
version_from: lib/LWP/UserAgent/iTMS_Client.pm
installdirs:  site
requires:
    Audio::M4P::QuickTime:         0.11
    Carp:                          0
    Compress::Zlib:                0
    Crypt::AppleTwoFish:           0.02
    Crypt::CBC:                    0
    Crypt::Rijndael:               0
    Digest::MD5:                   0
    MIME::Base64:                  0
    Test::More:                    0
    Time::HiRes:                   0
    URI::Escape:                   0
    XML::Twig:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
