--- #YAML:1.0
name:                LWP-UserAgent-iTMS_Client
version:             0.22
abstract:            Interact with the Apple iTunes Music Store
license:             ~
author:              
    - William Hererra (whererra@skylightview.com)
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    Carp:                          0
    Compress::Zlib:                0
    Crypt::AppleTwoFish:           0.02
    Crypt::CBC:                    0
    Crypt::Rijndael:               0
    DateTime:                      0
    Digest::MD5:                   0
    MIME::Base64:                  0
    Test::More:                    0
    URI::Escape:                   0
    XML::Twig:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
